### ISSUE TITLE
Set up ghcr

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/kasm-gis-workspace#5]
Users wanting to perform a geoCML deployment from this repo's base image may not want to build the image locally before deployment. We should automate the build process with ghcr, allowing users to pull the image directly from the container registry. 

Additionally, our CI/CD is failing because we do not currently have ghcr set up for this repo, (relic from the repo we forked to make this one). With ghcr, we can take full advantage of Github Actions to keep our base image up-to-date with each update coming into the repo.

**Comment by capsulecorplab** [comment]
Should be able to pull from GHCR now. Try pulling changes as of https://github.com/geoCML/kasm-gis-workspace/commit/aa662cf840498fe225982f4c1a36859b8163a9ec and running `docker-compose pull` to test that it works

**Comment by TristanDamron** [comment]
Sweet! I am noticing one small issue--I get an error when I start up the container 
![image](https://user-images.githubusercontent.com/6404980/182763931-f4222cde-ff91-4ed9-bd37-8756a64d0790.png)

Could you please update docker-compose so that the CML in geoCML is lowercase?

**Comment by capsulecorplab** [comment]
Try it now? S/b fixed as of https://github.com/geoCML/kasm-gis-workspace/commit/5473ed1136bdddb359ac2b6131941a75da45f87c!

**Comment by TristanDamron** [comment]
LGTM! :100:
